### ISSUE TITLE
Broken links in Readme.md

### ISSUE THREAD

**Issue by gicking** [Community-PIO-CH32V/platform-ch32v#16]
The following links in Readme.md don't exist
  - [Home](https://registry.platformio.org/platforms/platformio/ch32v) (home page in the PlatformIO Registry)
  - [Documentation](https://docs.platformio.org/page/platforms/ch32v.html) (advanced usage, packages, boards, frameworks, etc.)
  - [documentation](https://docs.platformio.org/page/platforms/ch32v.html) at bottom of page

I suspect(!) these will be created once ch32v platform is released...? If yes, please just close this issue

**Comment by maxgerhardt** [comment]
Right. I just copy-pasted the template from the other platforms and replaced the name.

This definitely needs a correct / custom README as I think integration of this platform into the official PlatformIO repos will be here soon.

Tracked in #12 too.

**Comment by maxgerhardt** [comment]
Fixed through 06ca19ef8f231521c78374d65129a8449aaa5d14
