### ISSUE TITLE
Any CAN bus usage examples?

### ISSUE THREAD

**Issue by martiinezz** [Community-PIO-CH32V/platform-ch32v#23]
CH32V307 is also very interesting as it has 2 x CAN 2.0 built in. 
Would be nice to have at least one example how to use it.

**Comment by maxgerhardt** [comment]
I think it's a good idea if I upload all the "EVT" / evaluation files from WCH here, they have all the examples (`EXAM`). 

![grafik](https://user-images.githubusercontent.com/26485477/224555058-b8a57b02-d08c-438f-8d3e-0d04c3371cd3.png)

You can download it from https://www.wch.cn/downloads/CH32V307EVT_ZIP.html too. I'll also need to add documentation on how to import those examples into PlatformIO, but basically it's: Copy all source files from the "User" folder in an example to `src/` of the PlatformIO project, except the `system_ch32v30x.c/.h`.
