### ISSUE TITLE
Could not find the package with 'ch32v' 

### ISSUE THREAD

**Issue by ogneyar** [Community-PIO-CH32V/platform-ch32v#27]
Hello, help me figure out if I have an error on Ubuntu or Windows 10

on Ubuntu Error: Could not find the package with 'ch32v' requirements for your system 'linux_x86_64'

A similar error occurs on Windows

**Comment by maxgerhardt** [comment]
The platform is not listed in the PIO registry. You must install it manually once per documentation.

https://pio-ch32v.readthedocs.io/en/latest/installation.html

**Comment by ogneyar** [comment]
> 

Thank you
