### ISSUE TITLE
Problems with uploading firmware ch32v003f4p6

### ISSUE THREAD

**Issue by Alex-IC** [Community-PIO-CH32V/platform-ch32v#30]
### Discussed in https://github.com/Community-PIO-CH32V/platform-ch32v/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **Alex-IC** June 18, 2023</sup>
I’m trying to upload code via Platformio ->Upload and getting an error:

```
Total         1875
<lambda>(["upload"], [".pio\build\genericCH32V003F4P6\firmware.elf"])
AVAILABLE: isp, minichlink, wch-link
CURRENT: upload_protocol = wch-link
openocd -c "debug_level 2" -s C:\Users\Alexey\.platformio\packages\tool-openocd-riscv-wch\bin -s C:\Users\Alexey\.platformio\packages\tool-openocd-riscv-wch\scripts -f wch-riscv.cfg -c init -c halt -c "program {.pio\build\genericCH32V003F4P6\firmware.elf} verify reset" -c shutdown
Open On-Chip Debugger 0.11.0+dev-02415-gfad123a16-dirty (2023-01-03-10:00)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
debug_level: 2

Info : only one transport option; autoselect 'sdi'
Warn : Transport "sdi" was already selected
Ready for Remote Connections
Info : WCH-LinkE  mode:RV version 2.7 
Info : wlink_init ok

*** [upload] Error 1
========================================================================== [FAILED] Took 2.58 seconds ======================

```
What could be the problem? Through the WCH Link Utility it is stitched without problems.
Chip ch32f008f4p6
VSCode 1.79.2
PlatformIO 6.1.7
OS Windows_NT x64 10.0.0.17763</div>

**Comment by maxgerhardt** [comment]
>Info : WCH-LinkE  mode:RV version 2.7 

The firmware on mine is 2.8.

```
Info : only one transport option; autoselect 'sdi'
Warn : Transport "sdi" was already selected
Ready for Remote Connections
Info : WCH-LinkE  mode:RV version 2.8
```
I think since we're using the latest OpenOCD you also need the latest firmware version. 

Can you install the very latest version of MounRiver Studio Version and check if you can do a firmware update of your WCH-LinkE to v2.8?

**Comment by maxgerhardt** [comment]
Huh, even I am not on the latest version. After the latest MounRiver Studio update, when I go Flash->Download in a CH32V003 template project, it asks me to update too.

![grafik](https://github.com/Community-PIO-CH32V/platform-ch32v/assets/26485477/2b034fb0-b097-488c-97e9-637aed59d136)

![grafik](https://github.com/Community-PIO-CH32V/platform-ch32v/assets/26485477/280a5fd7-1ccb-4871-95eb-1b25054f83bc)

Welp, let's try this out then.. Worst case I have to update OpenOCD again everywhere.

Edit: Update at least worked.
```
------------ Begin flash process of "obj\CH32V003A4M6.hex" ------------ 
13:41:43:050 >> Current project vendor is WCH, debugger is WCH-Link

13:41:43:050 >> Attempt to open link device and upgrade firmware if necessary...
13:42:27:721 >> Firmware upgrade success. Please click the button again.
Firmware upgrade success. Please click the button again.

---------------------------------End ----------------------------------
```

**Comment by maxgerhardt** [comment]
And PlatformIO still works fine with the updated firmware version.

![grafik](https://github.com/Community-PIO-CH32V/platform-ch32v/assets/26485477/cb86dced-d146-44ef-9384-9d983ee4dc5a)

**Comment by Alex-IC** [comment]
Wow, thanks a lot, this solution worked. Updated WCH-LinkE to version 2.9 and now everything works, both firmware and debugging.
