### ISSUE TITLE
Can the C language format be set to the C99 version?

### ISSUE THREAD

**Issue by Witawat** [Community-PIO-CH32V/platform-ch32v#40]
I've tried migrating code from MRS, but it runs on C99, causing some code to not compile. correctly

![image](https://github.com/Community-PIO-CH32V/platform-ch32v/assets/4926369/781393dd-560d-43fd-a57e-e8e1e7c4f089)

Now I've tested three IDEs to find the one that's easiest to use.
1. MRS
2. Clion
3. VSCode

But there's a problem with C99.

**Comment by maxgerhardt** [comment]
I thought in C you always had to use
```c
#include <stdbool.h>
```
to get the `bool` type. Per https://en.cppreference.com/w/c/types/boolean.

**Comment by Witawat** [comment]
![image](https://github.com/Community-PIO-CH32V/platform-ch32v/assets/4926369/646b9235-f540-4df3-89a2-a0433410356e)

this not support print %f ? 

this config on MRS is work

![image](https://github.com/Community-PIO-CH32V/platform-ch32v/assets/4926369/c7893c96-baec-47c2-8cec-06323f4d766b)

i add 

build_unflags = -lprintf
build_flags = -lprintfloat

not work

![image](https://github.com/Community-PIO-CH32V/platform-ch32v/assets/4926369/6e8669e7-6b6c-42d3-bcdc-a8e213623275)
