### ISSUE TITLE
config not support printf %f can not display

### ISSUE THREAD

**Issue by Witawat** [Community-PIO-CH32V/platform-ch32v#41]
![image](https://github.com/Community-PIO-CH32V/platform-ch32v/assets/4926369/646b9235-f540-4df3-89a2-a0433410356e)

this not support print %f ? 

this config on MRS is work

![image](https://github.com/Community-PIO-CH32V/platform-ch32v/assets/4926369/c7893c96-baec-47c2-8cec-06323f4d766b)

i add 

build_unflags = -lprintf
build_flags = -lprintfloat

not work

![image](https://github.com/Community-PIO-CH32V/platform-ch32v/assets/4926369/6e8669e7-6b6c-42d3-bcdc-a8e213623275)

_Originally posted by @Witawat in https://github.com/Community-PIO-CH32V/platform-ch32v/issues/40#issuecomment-1792062660_

**Comment by maxgerhardt** [comment]
I just use
```ini
[env]
platform = ch32v
framework = noneos-sdk
monitor_speed = 115200

[env:ch32v003f4p6_evt_r0]
board = ch32v003f4p6_evt_r0
build_flags = -lprintfloat
```
with
```c
#include <ch32v00x.h>
#include <debug.h>

void NMI_Handler(void) __attribute__((interrupt("WCH-Interrupt-fast")));
void HardFault_Handler(void) __attribute__((interrupt("WCH-Interrupt-fast")));

int main(void)
{
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_2);
	SystemCoreClockUpdate();
	Delay_Init();
	USART_Printf_Init(115200);

	while (1)
	{
		Delay_Ms(1000);
		printf("Test: %f\n", 1.234f);
	}
}

void NMI_Handler(void) {}
void HardFault_Handler(void)
{
	while (1)
	{
	}
}
```
and that works okay.

![grafik](https://github.com/Community-PIO-CH32V/platform-ch32v/assets/26485477/71e9df51-9924-4cbd-b34b-63476051428c)

The other path would be
```ini
build_flags = -Wl,-u_printf_float
```
but the CH32V003 does not have enough flash for that.

**Comment by maxgerhardt** [comment]
The problem rather seems to be that with `-lprintfloat`, the `%hu` specifiers are not evaluated anymore, which messes up which argument is getting read next by printf(). Try and use simpler ones like just `%u` or even `%d` and cast the argument in the printf() call accrodingly.
