### ISSUE TITLE
pls support CH59X

### ISSUE THREAD

**Issue by wc7086** [Community-PIO-CH32V/platform-ch32v#43]
https://www.wch.cn/downloads/CH592DS1_PDF.html

**Comment by maxgerhardt** [comment]
Support for all CH59x chips added in 52794e49876c7ccca888449da8e1a13076317569 and https://github.com/Community-PIO-CH32V/framework-wch-noneos-sdk/commit/4b679d62eda2b2d3fc23048dde8158d8b95c660d and tested to compile properly with the `blinky-none-os-ch5xx` example.

**Comment by maxgerhardt** [comment]
Also BLE example added in a4fcf43d4eba5672c679a7dfed1d55bd0cd2f8c1 as `ble-hid-ch59x`, more to be found in https://github.com/openwch/ch592/tree/main/EVT_V1.0/EXAM/BLE.
