### ISSUE TITLE
CH32V307 access ports outside of PA and PB

### ISSUE THREAD

**Issue by LovelyA72** [Community-PIO-CH32V/platform-ch32v#54]
I tested the blinky sketch with PD10 and PD11 but nothing happens. PA1 and PA2 works just fine. According to the board variant file there are only definitions for PA and PB. Is there any way for me to access those additional ports?

**Comment by maxgerhardt** [comment]
For the `genericCH32V307VCT6` board, the variant only defines PA and PB pins in its `digitalPin` array. Indeed none of the PC, PD and PE ports are listed in that arary.

https://github.com/openwch/arduino_core_ch32/blob/c40c5c8095060c523e635b99426314fab56fe12c/variants/CH32V30x/CH32V307VCT6/variant_CH32V307VCT6.cpp#L19-L44

They can easily be added as new array entries, e.g., `PD_10`, `PD_11` then become available as pin number 22 and 23. Of course, [NUM_DIGITAL_PINS](https://github.com/openwch/arduino_core_ch32/blob/c40c5c8095060c523e635b99426314fab56fe12c/variants/CH32V30x/CH32V307VCT6/variant_CH32V307VCT6.h#L63C9-L63C33) has to be increased by 2, too.

In any case, this is an issue with the Arduino core, not this platform. Please file an issue against https://github.com/openwch/arduino_core_ch32/, or even a PR if you can.

**Comment by maxgerhardt** [comment]
An escape hatch are always the underlying functions. For example, this should be equivalent, but is of course not Arduino-style.
```cpp
#include <Arduino.h>

void setup()
{
  // pinMode(PD11, OUTPUT);
  pin_function(PD_11, CH_PIN_DATA(CH_MODE_OUTPUT_50MHz, CH_CNF_OUTPUT_PP, 0, 0));
}

void loop()
{
  digitalWriteFast(PD_11, HIGH);
  delay(1000);
  digitalWriteFast(PD_11, LOW);
  delay(1000);
}
```
