### ISSUE TITLE
Arduino for CH32V203RB

### ISSUE THREAD

**Issue by theaudiobible** [Community-PIO-CH32V/platform-ch32v#55]
Hello Max,

Are you happy to add this support for CH32V203RB?  I'm currently using it and it seems to work ok:
https://github.com/Community-PIO-CH32V/platform-ch32v/pull/52

Thanks!

**Comment by maxgerhardt** [comment]
Fixed in https://github.com/Community-PIO-CH32V/platform-ch32v/commit/d9663011522ffa485b465a2dcdcebafa3970bcd1
