### ISSUE TITLE
May need update of boards at platform-ch32v: CH32V203G8

### ISSUE THREAD

**Issue by ldab** [Community-PIO-CH32V/platform-ch32v#59]
Interesting, also possibly added a new chip there. May need update of boards at platform-ch32v.

_Originally posted by @maxgerhardt in https://github.com/Community-PIO-CH32V/framework-wch-noneos-sdk/pull/4#discussion_r1620929970_

**Comment by ldab** [comment]
Note to self, once https://github.com/Community-PIO-CH32V/framework-wch-noneos-sdk/pull/4 is merged

**Comment by maxgerhardt** [comment]
Never mind, https://github.com/Community-PIO-CH32V/platform-ch32v/blob/develop/boards/genericCH32V203G8R6.json already exists.
