### ISSUE TITLE
Is there any way to make PIO-CH32V work with Winusb?

### ISSUE THREAD

**Issue by Rockwell1799** [Community-PIO-CH32V/platform-ch32v#64]
I'm on windows 11 and the vscode with PIO-CH32 is working fine with the CH32V003FUN project,but I want to use the minichlink ,but unfortunately it's only working with Winusb not the proprietary CH-link driver and Vscode with PIO32 doesn't work with Winusb.
So,is there any way to still use Vscode and minichlink at the same time?
TIA

**Comment by maxgerhardt** [comment]
Please try the upload protocols
```
upload_protocol = minichlink
```
and
```
upload_protocol = wlink
```

**Comment by Rockwell1799** [comment]
Thank you! I guess you meant either minichlink or wlink?

**Comment by maxgerhardt** [comment]
Yes. They will use <https://github.com/cnlohr/ch32v003fun/tree/master/minichlink> or <https://github.com/ch32-rs/wlink/> respectively. However, with `minichlink` I have not yet integrated the debugging feature, there are some problems with it; so they can only *upload* properly, not debug.

**Comment by Rockwell1799** [comment]
Thank you for your prompt reply!
Let's say if I want to use wlink, in which path do I have to copy wlink.exe?

**Comment by maxgerhardt** [comment]
None at all. The platform manages it internally. If you set `upload_protocol = wlink`, it will download the package as specified in [the platform.json](https://github.com/Community-PIO-CH32V/platform-ch32v/blob/55aad82147ce373f723a34071f7552e10fff992d/platform.json#L148-L153) into `C:\Users\<user>\.platformio\packages\tool-wlink` and call it from there when it's time to upload. You don't need to manually download anything, only tell PlatformIO that you want to use that upload protocol with the line in the `platformio.ini`. Automatic package management is a key feature of PlatformIO.

**Comment by Rockwell1799** [comment]
Thank you Max, you are very helpful! 
I'm going to try that when I get back home.
