### ISSUE TITLE
Is the pwm of ch32v00x working now?

### ISSUE THREAD

**Issue by xiaowine** [Community-PIO-CH32V/platform-ch32v#66]
Is the pwm of ch32v00x working now?
I use analogWrite without a response

**Comment by maxgerhardt** [comment]
`analogWrite()` for CH32V003 should be working fine on these pins.

https://github.com/openwch/arduino_core_ch32/blob/273620c809ba4cc3c6928543c6929634de8e50ba/variants/CH32V00x/CH32V003F4/PeripheralPins.c#L64-L76

**Comment by maxgerhardt** [comment]
Reopen if you still need help.
