### ISSUE TITLE
Can we get support for ch32v317?

### ISSUE THREAD

**Issue by ZhiqiangChengDevq** [Community-PIO-CH32V/platform-ch32v#72]

**Comment by ZhiqiangChengDevq** [comment]
This is a my makefile project, I hope this can help you.(@ MacOS)
[CH317.zip](https://github.com/user-attachments/files/17014019/CH317.zip)

**Comment by maxgerhardt** [comment]
Sure, I'll get it added. I already did the necessary WCH SDK update some days ago. https://github.com/Community-PIO-CH32V/framework-wch-noneos-sdk/pull/9

![grafik](https://github.com/user-attachments/assets/d2186a63-3160-4862-933e-1aa04ce2c52c)

**Comment by maxgerhardt** [comment]
These chips are weird. Their SDK and used macros are pretty much the same as for some CH32V307 chips. Even the Flash/RAM is the same. Seems they only have a peripheral more or something? At least their SVD file is different.

Added in cf9419280a25a29de91a562b74dcab487daff071 and 2e177e7f592ed56fe333021c0d1f31344f96afb0, so now we have thesse boards.

![grafik](https://github.com/user-attachments/assets/606ba810-5188-468c-b25b-0a2744ac3923)

**Comment by ZhiqiangChengDevq** [comment]
Thank you for your support. Wishing you a pleasant life!
