### ISSUE TITLE
Error: Failed to access data for an ELF segment???

### ISSUE THREAD

**Issue by Rockwell1799** [Community-PIO-CH32V/platform-ch32v#77]
Hello
I have an issue with the following code:
```
#include <config.h>                               // user configurations
#include <system.h>                               // system functions
#include <gpio.h>                                 // GPIO functions
#include <debug_serial.h>                          // serial debug functions
volatile uint32_t count;
// ===================================================================================
// Main Function
// ===================================================================================
int main(void) {
  // Setup
  PIN_output(PIN_LED);                            // set LED pin to output

  // Loop
  while(1) {
    PIN_toggle(PIN_LED);                            // toggle LED
    DLY_ms(1000);                                  // wait a bit
    DEBUG_newline();
    DEBUG_printD(count++);                         // send string
  }
}
```
The code does compile, but I get the error: Failed to access data for an ELF segment.
When I remove the last 2 lines, the code uploads without any issue.
Does someone have an idea why I'm getting this error?
TIA
![Code_aFmWRBOoyT](https://github.com/user-attachments/assets/6332e666-1399-4083-b8bc-af09f30d4d8c)

**Comment by maxgerhardt** [comment]
Can you flash with `upload_protocol = wch-link` fine? What about `upload_protocol = minichlink`?

**Comment by Rockwell1799** [comment]
I can't use minichlink,because I'm not using the winusb driver.

**Comment by maxgerhardt** [comment]
Okay, then `upload_protocol = wch-link` should work if you use the WCH driver.

Can you upload the **exact** project files? It seems to be https://github.com/wagiminator/Development-Boards/blob/main/CH32X033F8P6_DevBoard/software/debug_serial but with some modifications.

**Comment by Rockwell1799** [comment]
With wch-link, it uploads the code, but the LED is not blinking anymore!
![Code_65tUdmfQ8W](https://github.com/user-attachments/assets/1a1e58e3-f1d6-4e1b-b370-8b67fd1af754)

[blink.zip](https://github.com/user-attachments/files/17758476/blink.zip)
I've attached the project files as zip below.

**Comment by maxgerhardt** [comment]
Look in the debugger. You're hanging up in the DEBUG_write() function which waits for the character to be written (Transmit Empty), but that can never happen because your `main()` function never initializes the UART by calling into `DEBUG_init()`.

![grafik](https://github.com/user-attachments/assets/23551054-e3f2-4597-9444-4ee784f80e63)

A main function of 
```cpp
int main(void) {
  // Setup
  PIN_output(PIN_LED);                            // set LED pin to output
  DEBUG_init();
  
  // Loop
  while(1) {
    PIN_toggle(PIN_LED);                            // toggle LED
    DLY_ms(1000);                                  // wait a bit
    DEBUG_newline();
    DEBUG_printD(count++);                         // send string
  }
}
```
gets the LED blinking again.

**Comment by maxgerhardt** [comment]
Thanks to your project, I can reproduce the error
```
22:30:04 [INFO] Connected to WCH-Link v2.14(v34) (WCH-LinkE-CH32V305)
22:30:04 [INFO] Attached chip: CH32X035 [CH32X035F8U6] (ChipID: 0x035e0601)
22:30:04 [INFO] Chip ESIG: FlashSize(62KB) UID(cd-ab-28-c5-49-bc-3e-2d)
22:30:04 Error: Failed to access data for an ELF segment.
[INFO] Flash protected: false
22:30:04 [INFO] Read .pio\build\CH32X035\firmware.elf as ELF format
*** [upload] Error 1
```
and will look into it. Maybe we need a `wlink.exe` update, or a bug should be opened there.

**Comment by maxgerhardt** [comment]
This error is reproducable in the latest version of wlink and now tracked in https://github.com/ch32-rs/wlink/issues/77.

Please use `upload_protocol = wch-link` since it works fine.

You can also debug with it. Just open the debug sidepanel and click on the green Play button next to "PIO Debug". You can even view all perpiheral registers.

![grafik](https://github.com/user-attachments/assets/10bb58cc-9a50-457c-81cb-a7e33d0f78b3)

**Comment by maxgerhardt** [comment]
Will update the PlatformIO binaries for `wlink` once https://github.com/ch32-rs/wlink/pull/79 is released.

**Comment by maxgerhardt** [comment]
The updated binaries have been submitted to registry as `tool-wlink` and are awaiting approval by the PlatformIO team.

>The package has been accepted for moderation. We will notify you on email when process it.

**Comment by maxgerhardt** [comment]
All binaries were actually updated in https://github.com/Community-PIO-CH32V/tool-wlink/ (PIO registry unused for that package), so it should all work right now.
