### ISSUE TITLE
enable and disable code protect using minichlink

### ISSUE THREAD

**Issue by RhonyD** [Community-PIO-CH32V/platform-ch32v#79]
how to enable and disable code protect using minichlink?

**Comment by maxgerhardt** [comment]
According to https://github.com/cnlohr/ch32v003fun/blob/bf73d9ad18b525059e5b80b1052a3c4dccc3463b/minichlink/minichlink.c#L733-L734 with the `-P` flag, so you could say in the `platformio.ini`
```ini
upload_flags = -P
```
(or add it onto maybe other existing `upload_flags`).

You may not be able to flash again after that, until read protection is disabled again, not sure.  `-p` will unprotect the flash again.

**Comment by RhonyD** [comment]
I can do it using the mourn river ide and then going to the configure uploader section, But it will be convenient to do so from within the vscode environment. Please see if it is possible.

**Comment by RhonyD** [comment]
in minichlink when given ./minichlink -p following are the outputs

![image](https://github.com/user-attachments/assets/4519cb3c-4452-4027-9f20-c978079a0feb)
![image](https://github.com/user-attachments/assets/80d324f4-3683-44f1-a1d2-2cf80f81e506)
 this shows that enable and disable code protect  can be done using minichlink but in case of vscode it's not possible yet.

**Comment by maxgerhardt** [comment]
Fixed in https://github.com/Community-PIO-CH32V/platform-ch32v/commit/9078ce4b9211753d7cb088ec0bf3cc351515d0a5

![grafik](https://github.com/user-attachments/assets/8803baae-45de-40ff-be4f-3dc3ad4ba598)

**Comment by RhonyD** [comment]
Thanks Bro, it worked like a charm, GREAT JOB.... KUDOS TO YOU....
